import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "Aeso App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        style={{ visibility: "visible" }}
        className={`antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
