import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Footer } from "@/components/layout/Footer";

export const metadata = {
  title: "Aeso App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" style={{ overflowX: "hidden" }}>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=DM+Serif+Display:ital@0;1&family=Darker+Grotesque:wght@300..900&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Darker+Grotesque:wght@300..900&display=swap" rel="stylesheet" />
      </head>
      <body
        style={{ visibility: "visible", fontFamily: "Darker Grotesque" }}
        className={`antialiased !font-serif overflow-x-hidden`}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
